# Generated by Django 5.1 on 2024-11-16 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertestimonial',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
