# Generated by Django 5.1 on 2024-10-07 15:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='detail_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
