# Generated by Django 5.1 on 2024-10-11 10:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
